  version: "3.8"
  services:
    backend:
      container_name: financialservice_backend
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - MONGO_URI=mongodb://api_user:api_pwd@mongodb:27020/financialservice
      command: "python run.py runserver 0.0.0.0:8001"
      ports:
        - 8001:8001
      volumes:
        - .:/app
      depends_on:
        - mongodb

    mongodb:
      container_name: financialservice_db
      image: mongo:latest
      restart: always
      environment:
        - MONGO_INITDB_DATABASE=financialservice
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
        - ./mongodb/data:/data/db
        - ./mongodb/init-db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

      ports:
        - 27020:27017